language: php
php:
  - '7.1'
before-script:
  - composer self-update
  - composer install --no-interaction
script:
  - cp .env.travis .env
  - ./home/travis/build/guicunha/promocode/vendor/bin/phpunit